[package]
name = "uu_cp"
version = "0.0.28"
authors = [
  "Jordy Dickinson <jordy.dickinson@gmail.com>",
  "Joshua S. Miller <jsmiller@uchicago.edu>",
  "uutils developers",
]
license = "MIT"
description = "cp ~ (uutils) copy SOURCE to DESTINATION"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/cp"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2021"

readme.workspace = true

[lib]
path = "src/cp.rs"

[dependencies]
clap = { workspace = true }
filetime = { workspace = true }
libc = { workspace = true }
quick-error = { workspace = true }
selinux = { workspace = true, optional = true }
uucore = { workspace = true, features = [
  "backup-control",
  "entries",
  "fs",
  "perms",
  "mode",
  "update-control",
] }
walkdir = { workspace = true }
indicatif = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { workspace = true, features = [
  "Win32_System_IO",
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
  "Win32_Security",
  "Win32_System_Ioctl",
] }

[target.'cfg(unix)'.dependencies]
xattr = { workspace = true }
exacl = { workspace = true, optional = true }

[[bin]]
name = "cp"
path = "src/main.rs"

[features]
feat_selinux = ["selinux"]
feat_acl = ["exacl"]
